import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout";

const urbanistSans = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Estate",
  description: "Generated by estate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanistSans.variable}  antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
